# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Node.js Package

on:
  release:
    types: [created]
  push:
    branches:
      - master
      - dev/test

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      # 拉代码 安装node
      - name: CheckOut
        uses: actions/checkout@v3
      - name: Use Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/

      # 添加缓存，逻辑和CI Workflow里的一样
      - name: Cache
        id: cache-dependencies
        uses: actions/cache@v3
        with:
          path: |
            **/node_modules
          key: ${{hashFiles('**/pnpm-lock.yaml')}}

      # 安装依赖。命中缓存则跳过此步
      - name: Installing Dependencies
        if: steps.cache-dependencies.outputs.cache-hit != 'true'
        run: |
          npm i pnpm -g
          pnpm install

      # 打包
      - name: Build
        run: |
          cd packages/icon-vue-components
          pnpm build
          npm publish --access public

        # - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
